/**
 * Códigos de error del módulo de álbumes
 */
export enum AlbumErrorCode {
  ALBUM_NOT_FOUND = 'ALBUM_NOT_FOUND',
  ALBUM_PRIVATE = 'ALBUM_PRIVATE',
  ALBUM_PERMISSION_DENIED = 'ALBUM_PERMISSION_DENIED',
  ALBUM_OWNER_REQUIRED = 'ALBUM_OWNER_REQUIRED',
  ALBUM_ORGANIZER_REQUIRED = 'ALBUM_ORGANIZER_REQUIRED',
  ALBUM_BANNED = 'ALBUM_BANNED',
  ALBUM_INVITE_INVALID = 'ALBUM_INVITE_INVALID',
  ALBUM_INVITE_EXPIRED = 'ALBUM_INVITE_EXPIRED',
  ALBUM_OWNER_SCAN_FORBIDDEN = 'ALBUM_OWNER_SCAN_FORBIDDEN',
  ALBUM_ALREADY_SCANNED = 'ALBUM_ALREADY_SCANNED',
  ALBUM_NOT_SCANNED = 'ALBUM_NOT_SCANNED',
  PARTICIPANT_NOT_FOUND = 'PARTICIPANT_NOT_FOUND',
}
