/**
 * Códigos de error del módulo de chat
 */
export enum ChatErrorCode {
  // Messages
  CHAT_FILE_NOT_FOUND = 'CHAT_FILE_NOT_FOUND',
  CHAT_MESSAGE_NOT_FOUND = 'CHAT_MESSAGE_NOT_FOUND',
  CHAT_MESSAGE_FORBIDDEN = 'CHAT_MESSAGE_FORBIDDEN',
  CHAT_MESSAGE_EDIT_UNSUPPORTED = 'CHAT_MESSAGE_EDIT_UNSUPPORTED',
  CHAT_MEDIA_MISMATCH = 'CHAT_MEDIA_MISMATCH',
  CHAT_MESSAGE_EMPTY = 'CHAT_MESSAGE_EMPTY',
  CHAT_MESSAGE_SEND_FAILED = 'CHAT_MESSAGE_SEND_FAILED',
  CHAT_VIDEO_TOO_LONG = 'CHAT_VIDEO_TOO_LONG',
  CHAT_AUDIO_TOO_LONG = 'CHAT_AUDIO_TOO_LONG',
  CHAT_MESSAGE_EDIT_FAILED = 'CHAT_MESSAGE_EDIT_FAILED',
  CHAT_MESSAGE_DELETE_FAILED = 'CHAT_MESSAGE_DELETE_FAILED',
  CHAT_MESSAGE_DELETE_MEDIA_FAILED = 'CHAT_MESSAGE_DELETE_MEDIA_FAILED',
  CHAT_MARK_AS_READ_FAILED = 'CHAT_MARK_AS_READ_FAILED',

  // View-Once
  CHAT_VIEW_ONCE_EXPIRED = 'CHAT_VIEW_ONCE_EXPIRED',
  CHAT_VIEW_ONCE_ALREADY_VIEWED = 'CHAT_VIEW_ONCE_ALREADY_VIEWED',
  CHAT_VIEW_ONCE_SENDER_FORBIDDEN = 'CHAT_VIEW_ONCE_SENDER_FORBIDDEN',
  CHAT_VIEW_ONCE_DOWNLOAD_FORBIDDEN = 'CHAT_VIEW_ONCE_DOWNLOAD_FORBIDDEN',

  // Members & Groups
  CHAT_MEMBER_NOT_FOUND = 'CHAT_MEMBER_NOT_FOUND',
  CHAT_MEMBER_INVALID_STATUS = 'CHAT_MEMBER_INVALID_STATUS',
  CHAT_ADMIN_REQUIRED = 'CHAT_ADMIN_REQUIRED',
  CHAT_MEMBER_ALREADY_ADMIN = 'CHAT_MEMBER_ALREADY_ADMIN',
  CHAT_MEMBER_NOT_ADMIN = 'CHAT_MEMBER_NOT_ADMIN',
  CHAT_CANNOT_KICK_SELF = 'CHAT_CANNOT_KICK_SELF',
  CHAT_GROUP_NOT_FOUND = 'CHAT_GROUP_NOT_FOUND',
  CHAT_GROUP_ALBUM_MISMATCH = 'CHAT_GROUP_ALBUM_MISMATCH',
  CHAT_GROUP_OWNER_REQUIRED = 'CHAT_GROUP_OWNER_REQUIRED',
  CHAT_USER_NOT_FOUND = 'CHAT_USER_NOT_FOUND',

  // Pinned Messages
  CHAT_PINNED_MESSAGE_NOT_FOUND = 'CHAT_PINNED_MESSAGE_NOT_FOUND',
  CHAT_PINNED_MESSAGE_FORBIDDEN = 'CHAT_PINNED_MESSAGE_FORBIDDEN',
  /** El mensaje YA está fijado. No es un problema de permisos: dos de los tres
   * sitios que usaban `CHAT_PINNED_MESSAGE_FORBIDDEN` significaban esto, y el
   * cliente le decía «no tenés permiso» a alguien que sí lo tiene. */
  CHAT_MESSAGE_ALREADY_PINNED = 'CHAT_MESSAGE_ALREADY_PINNED',

  // Reactions
  CHAT_REACTION_TOGGLE_FAILED = 'CHAT_REACTION_TOGGLE_FAILED',
}
