/**
 * Códigos de error generales del sistema
 */
export enum CommonErrorCode {
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  FILES_EMPTY = 'FILES_EMPTY',
  FILES_TOO_LARGE = 'FILES_TOO_LARGE',
  FILES_DIMENSIONS_TOO_LARGE = 'FILES_DIMENSIONS_TOO_LARGE',
  FILES_TOO_MANY = 'FILES_TOO_MANY',
  FILES_UNSUPPORTED_FORMAT = 'FILES_UNSUPPORTED_FORMAT',
  FILES_CONTENT_INVALID = 'FILES_CONTENT_INVALID',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',

  // Upload errors
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  UPLOAD_FILE_MISSING = 'UPLOAD_FILE_MISSING',
  UPLOAD_PUBLIC_ID_MISSING = 'UPLOAD_PUBLIC_ID_MISSING',
}
