export enum DownloadErrorCode {
  DOWNLOAD_MANIFEST_INVALID_REQUEST = 'DOWNLOAD_MANIFEST_INVALID_REQUEST',
  DOWNLOAD_MANIFEST_INVALID_ALBUM = 'DOWNLOAD_MANIFEST_INVALID_ALBUM',
  DOWNLOAD_MANIFEST_FILE_NOT_FOUND = 'DOWNLOAD_MANIFEST_FILE_NOT_FOUND',
  DOWNLOAD_MANIFEST_FORBIDDEN = 'DOWNLOAD_MANIFEST_FORBIDDEN',
  DOWNLOAD_MANIFEST_NOT_FOUND = 'DOWNLOAD_MANIFEST_NOT_FOUND',
  DOWNLOAD_MANIFEST_CREATE_FAILED = 'DOWNLOAD_MANIFEST_CREATE_FAILED',
  DOWNLOAD_MANIFEST_CANCEL_FAILED = 'DOWNLOAD_MANIFEST_CANCEL_FAILED',
  DOWNLOAD_MANIFEST_ITEM_COMPLETE_FAILED = 'DOWNLOAD_MANIFEST_ITEM_COMPLETE_FAILED',
  // Download jobs (server-side bulk, §9)
  DOWNLOAD_JOB_EMPTY = 'DOWNLOAD_JOB_EMPTY', // álbum/carpeta sin fotos PROFESSIONAL
  DOWNLOAD_JOB_TOO_MANY_PHOTOS = 'DOWNLOAD_JOB_TOO_MANY_PHOTOS', // > DOWNLOAD_JOB_MAX_PHOTOS
  DOWNLOAD_JOB_TOO_MANY_ACTIVE = 'DOWNLOAD_JOB_TOO_MANY_ACTIVE', // > MAX_ACTIVE_DOWNLOAD_JOBS_PER_USER (fix M4)
  DOWNLOAD_JOB_NOT_FOUND = 'DOWNLOAD_JOB_NOT_FOUND',
  DOWNLOAD_JOB_FORBIDDEN = 'DOWNLOAD_JOB_FORBIDDEN',
  DOWNLOAD_JOB_CREATE_FAILED = 'DOWNLOAD_JOB_CREATE_FAILED',
  DOWNLOAD_JOB_CANCEL_FAILED = 'DOWNLOAD_JOB_CANCEL_FAILED',
}
