export enum FolderErrorCode {
  FOLDER_NOT_FOUND = 'FOLDER_NOT_FOUND',
  FOLDER_ORGANIZER_REQUIRED = 'FOLDER_ORGANIZER_REQUIRED',
  FOLDER_NAME_CONFLICT = 'FOLDER_NAME_CONFLICT',
  FOLDER_MAX_COUNT_EXCEEDED = 'FOLDER_MAX_COUNT_EXCEEDED',
  FOLDER_ALBUM_MISMATCH = 'FOLDER_ALBUM_MISMATCH',
  // set-cover: la foto no es PROFESSIONAL ∈ esta carpeta (§6.3.1, fix H4)
  FOLDER_COVER_PHOTO_INVALID = 'FOLDER_COVER_PHOTO_INVALID',
}
