/**
 * Códigos de error del módulo de fotos y uploads
 */
export enum PhotoErrorCode {
  // Photos
  PHOTO_NOT_FOUND = 'PHOTO_NOT_FOUND',
  GUEST_POST_NOT_FOUND = 'GUEST_POST_NOT_FOUND',
  GUEST_POST_EMPTY = 'GUEST_POST_EMPTY',
  /** Editar una publicación ajena. Usaba `PHOTO_DELETE_FORBIDDEN`, cuya copia
   * habla de BORRAR fotos: el único caller es el PATCH de edición. */
  GUEST_POST_EDIT_FORBIDDEN = 'GUEST_POST_EDIT_FORBIDDEN',
  GUEST_VIDEO_TOO_LONG = 'GUEST_VIDEO_TOO_LONG',

  // Photo Tags
  PHOTO_TAG_ALREADY_EXISTS = 'PHOTO_TAG_ALREADY_EXISTS',
  PHOTO_TAG_FORBIDDEN = 'PHOTO_TAG_FORBIDDEN',
  PHOTO_TAG_NOT_GUEST_PHOTO = 'PHOTO_TAG_NOT_GUEST_PHOTO',
  PHOTO_TAG_NOT_FOUND = 'PHOTO_TAG_NOT_FOUND',

  // Uploads
  UPLOAD_ALL_FAILED = 'UPLOAD_ALL_FAILED',
  UPLOAD_ALBUM_MISMATCH = 'UPLOAD_ALBUM_MISMATCH',

  // Media Types
  VIDEO_NOT_FOUND = 'VIDEO_NOT_FOUND',
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  AUDIO_NOT_FOUND = 'AUDIO_NOT_FOUND',
}
