/**
 * Códigos de error del módulo de encuestas (polls)
 */
export enum PollErrorCode {
  // Options
  POLL_MIN_OPTIONS = 'POLL_MIN_OPTIONS',
  POLL_MAX_OPTIONS = 'POLL_MAX_OPTIONS',
  POLL_OPTION_EMPTY = 'POLL_OPTION_EMPTY',
  POLL_OPTIONS_UNIQUE = 'POLL_OPTIONS_UNIQUE',
  POLL_OPTION_INVALID = 'POLL_OPTION_INVALID',

  // Duration
  POLL_MIN_DURATION = 'POLL_MIN_DURATION',
  POLL_MAX_DURATION = 'POLL_MAX_DURATION',

  // Poll Status
  POLL_NOT_FOUND = 'POLL_NOT_FOUND',
  POLL_NOT_ACTIVE = 'POLL_NOT_ACTIVE',
  POLL_EXPIRED = 'POLL_EXPIRED',
  POLL_ALREADY_VOTED = 'POLL_ALREADY_VOTED',
}
