export enum StoryErrorCode {
  STORY_NOT_FOUND = 'STORY_NOT_FOUND',
  STORY_FORBIDDEN = 'STORY_FORBIDDEN',
  STORY_VIDEO_TOO_LONG = 'STORY_VIDEO_TOO_LONG',
  STORY_DELETE_FAILED = 'STORY_DELETE_FAILED',
  STORY_VIEW_FAILED = 'STORY_VIEW_FAILED',
}
