/**
 * Códigos de error del módulo de usuarios
 */
export enum UserErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_BANNED = 'USER_BANNED',
  USER_NO_CHANGES = 'USER_NO_CHANGES',
  USER_PENDING_UPDATE_NOT_FOUND = 'USER_PENDING_UPDATE_NOT_FOUND',
  /** La cuenta NO tiene contraseña seteada (cuenta legacy / sólo social). Usaba
   * `USER_INVALID_PASSWORD`, así que se le decía «la contraseña es incorrecta»
   * a quien no tiene ninguna: reintentaba para siempre. */
  USER_PASSWORD_NOT_SET = 'USER_PASSWORD_NOT_SET',
  USER_PHONE_TAKEN = 'USER_PHONE_TAKEN',
  USER_UPDATE_DEVICE_LOCALE_FAILED = 'USER_UPDATE_DEVICE_LOCALE_FAILED',
  USER_DELETE_FAILED = 'USER_DELETE_FAILED',
  USER_ALREADY_BANNED = 'USER_ALREADY_BANNED',
  USER_NOT_BANNED = 'USER_NOT_BANNED',
  USER_BAN_FAILED = 'USER_BAN_FAILED',
  USER_UNBAN_FAILED = 'USER_UNBAN_FAILED',
  USER_BAN_INVALID_EXPIRES_AT = 'USER_BAN_INVALID_EXPIRES_AT',
}
