export const ALBUM_SOCKET_EVENTS = {
  IN: {
    JOIN_ALBUM: 'join-album',
    LEAVE_ALBUM: 'leave-album',
    JOIN_STORY: 'join-story',
    LEAVE_STORY: 'leave-story',
  },
  OUT: {
    JOIN_SUCCESS: 'joined',
    JOIN_ERROR: 'join-error',
    ALBUM_DELETED: 'album-deleted',
    PARTICIPANT_KICKED: 'participant-kicked',
    ALBUM_MEMBER_ROLE_CHANGED: 'album-member-role-changed',
    ALBUM_UPDATED: 'album-updated',
    ALBUM_VISIBILITY_CHANGED: 'album-visibility-changed',
    TAG_ADDED: 'tag-added',
    TAGS_ADDED: 'tags-added',
    TAG_REMOVED: 'tag-removed',
    STORY_TAG_REMOVED: 'story.tag-removed',
    PARTICIPANT_JOINED: 'participant-joined',
    HIGHLIGHTS_UPDATED: 'highlights-updated',
    MEMIVO_MOMENTS_UPDATED: 'memivo.moments-updated',
    STORIES_UPDATED: 'stories.updated',
    STORY_VIEW_COUNT_UPDATED: 'story.view-count-updated',
    ALBUM_DELETED_RECEIVED: 'album-deleted-received',
    PARTICIPANT_KICKED_RECEIVED: 'participant-kicked-received',
    ALBUM_MEMBER_ROLE_CHANGED_RECEIVED: 'album-member-role-changed-received',
    ALBUM_UPDATED_RECEIVED: 'album-updated-received',
    ALBUM_VISIBILITY_CHANGED_RECEIVED: 'album-visibility-changed-received',
    POST_DELETED: 'post-deleted',
    STORY_COMMENT_CREATED: 'story-comment.created',
    STORY_POLL_RESULTS: 'story-poll.results',
    STORY_POLL_CLOSED: 'story-poll.closed',
  },
} as const;
