export const CHAT_SOCKET_EVENTS = {
  IN: {
    JOIN_GROUP: 'join-group',
    LEAVE_GROUP: 'leave-group',
  },
  OUT: {
    JOIN_ERROR: 'join-error',
    NEW_MESSAGE: 'new-message',
    MESSAGE_UPDATED: 'message-updated',
    MESSAGE_DELETED: 'message-deleted',
    USER_JOINED: 'user-joined',
    USER_LEFT: 'user-left',
    USER_KICKED: 'user-kicked',
    MEMBER_PROMOTED: 'member-promoted',
    MEMBER_DEMOTED: 'member-demoted',
    POLL_ACTIVE: 'poll-active',
    POLL_UPDATED: 'poll-updated',
    POLL_ENDED: 'poll-ended',
    GROUP_DELETED: 'group-deleted',
    GROUP_UPDATED: 'group-updated',
    MESSAGE_PINNED: 'message-pinned',
    MESSAGE_UNPINNED: 'message-unpinned',
    NEW_MESSAGE_RECEIVED: 'new-message-received',
    GROUP_CREATED_RECEIVED: 'group-created-received',
    GROUP_DELETED_RECEIVED: 'group-deleted-received',
    USER_KICKED_RECEIVED: 'user-kicked-received',
    ALBUM_ACCESS_REVOKED: 'album-chat-access-revoked',
    GROUP_UPDATED_RECEIVED: 'group-updated-received',
    REACTION_UPDATED: 'reaction-updated',
    VIEW_ONCE_OPENED: 'view-once-opened',
    VIEW_ONCE_EXPIRED: 'view-once-expired',
    LIVE_LOCATION_UPDATED: 'live-location-updated',
    LIVE_LOCATION_ENDED: 'live-location-ended',
  },
} as const;
