export enum ChatMessageType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  AUDIO = 'AUDIO',
  DOCUMENT = 'DOCUMENT',
  LOCATION = 'LOCATION',
  POLL = 'POLL',
  SYSTEM = 'SYSTEM',
  SHARED_POST = 'SHARED_POST',
  STICKER = 'STICKER',
}
