export enum AlbumActionType {
  MEMBER_KICKED = 'MEMBER_KICKED',
  ORGANIZER_PROMOTED = 'ORGANIZER_PROMOTED',
  ORGANIZER_DEMOTED = 'ORGANIZER_DEMOTED',
  GUEST_POST_DELETED = 'GUEST_POST_DELETED',
  GUEST_PHOTOS_DELETED = 'GUEST_PHOTOS_DELETED',
  PHOTO_DELETED = 'PHOTO_DELETED',
  ALL_PHOTOS_DELETED = 'ALL_PHOTOS_DELETED',
  FOLDER_DELETED = 'FOLDER_DELETED',
  STORY_DELETED = 'STORY_DELETED',
  COMMENT_DELETED = 'COMMENT_DELETED',
  RESPONSE_DELETED = 'RESPONSE_DELETED',
  STORY_COMMENT_DELETED = 'STORY_COMMENT_DELETED',
  ALBUM_UPDATED = 'ALBUM_UPDATED',
  ALBUM_VISIBILITY_CHANGED = 'ALBUM_VISIBILITY_CHANGED',
  /**
   * El dueño rotó el acceso: QR nuevo + invite-links revocados. Deja rastro
   * porque invalida TODOS los links repartidos hasta ese momento — es la acción
   * de álbum con más alcance sobre gente de afuera, y sin registro nadie puede
   * explicar después por qué un link dejó de funcionar.
   */
  ALBUM_ACCESS_RESET = 'ALBUM_ACCESS_RESET',
  ALBUM_COVER_CHANGED = 'ALBUM_COVER_CHANGED',
  FOLDER_CREATED = 'FOLDER_CREATED',
  FOLDER_RENAMED = 'FOLDER_RENAMED',
  FOLDER_COVER_SET = 'FOLDER_COVER_SET',
}
