export const DownloadContext = {
  PROFESSIONAL_PHOTOS_SELECTION: 'PROFESSIONAL_PHOTOS_SELECTION',
  CHAT_FILE: 'CHAT_FILE',
  PROFESSIONAL_PHOTOS_FOLDER_ALL: 'PROFESSIONAL_PHOTOS_FOLDER_ALL',
  PROFESSIONAL_PHOTOS_FOLDERS_SELECTION: 'PROFESSIONAL_PHOTOS_FOLDERS_SELECTION',
} as const;

export type DownloadContext =
  (typeof DownloadContext)[keyof typeof DownloadContext];
